// templates/assets/page.vue
<script>
// Route Path
import createStore from '// Redux here';
const redux = createStore(window.STORAGE);

export default class Application {
    el: '#app',
    render: h => h(this),
    state: redux,
    template: `<h1 style="text-align: center;">Hello World</h1>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.17/vue.min.js" async><script>`,
    // needs hot reloading
}
</script>

// templates/assets/page.jsx
import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import createStore from '// Redux here';
import Application from './component';

import '// Route Path';

const dest = document.getElementById('app');
const store = createStore(window.STORAGE || {});

const application = (
    <Provider store={store}>
		<Application />
    </Provider>
);

ReactDOM.render(application, dest);

/* eslint-disable */
if (module.hot) {
	module.hot.accept([
		'./component',
		'// Redux here',
		'// Route Path',
	], () => {
		const newStore = createStore(window.STORAGE || {});

		const newApplication = (
			<Provider store={newStore}>
				<Application />
			</Provider>
        );
        
		ReactDOM.render(newApplication, dest);
	});
}
